"""GitHub integration module"""

import asyncio
from typing import List, Dict, Any
from datetime import datetime
from github import Github, GithubException


class GitHubManager:
    """Manages GitHub integrations and PR creation"""

    def __init__(self, token: str, repo_name: str):
        self.github = Github(token)
        self.repo = self.github.get_repo(repo_name)

    async def create_optimization_pr(
        self,
        optimizations: List[Dict[str, Any]],
        run_date: datetime
    ) -> str:
        """
        Create PR with automated optimizations

        Args:
            optimizations: List of optimizations to apply
            run_date: Date of analysis

        Returns:
            URL of created PR
        """
        try:
            # Create new branch
            branch_name = f"monthly-optimizations-{run_date.strftime('%Y-%m')}"
            base_branch = self.repo.default_branch

            # Get base commit
            base_commit = self.repo.get_branch(base_branch).commit

            # Create new branch
            self.repo.create_git_ref(
                ref=f"refs/heads/{branch_name}",
                sha=base_commit.sha
            )

            # Apply optimizations
            for opt in optimizations:
                if opt['type'] == 'database_index':
                    await self._create_migration_file(opt, branch_name)
                elif opt['type'] == 'dependency_update':
                    await self._update_package_json(opt, branch_name)

            # Create PR
            pr_title = f"🚀 Monthly Optimizations - {run_date.strftime('%B %Y')}"
            pr_body = self._generate_pr_body(optimizations, run_date)

            pr = self.repo.create_pull(
                title=pr_title,
                body=pr_body,
                head=branch_name,
                base=base_branch
            )

            # Add labels
            pr.add_to_labels('monthly-optimization', 'automated')

            return pr.html_url

        except GithubException as e:
            raise Exception(f"Failed to create PR: {e}")

    async def _create_migration_file(
        self,
        optimization: Dict[str, Any],
        branch: str
    ):
        """Create database migration file"""
        timestamp = datetime.now().strftime('%Y%m%d%H%M%S')
        filename = f"supabase/migrations/{timestamp}_add_index_{optimization['table']}.sql"

        content = f"""-- Monthly Optimization: {optimization['title']}
-- Generated by Monthly Value Agent

{optimization['sql']}
"""

        self.repo.create_file(
            path=filename,
            message=f"Add index to {optimization['table']}",
            content=content,
            branch=branch
        )

    async def _update_package_json(
        self,
        optimization: Dict[str, Any],
        branch: str
    ):
        """Update package.json with dependency updates"""
        try:
            # Get current package.json
            file = self.repo.get_contents("package.json", ref=branch)
            import json

            package_data = json.loads(file.decoded_content.decode())

            # Update dependency
            dep_name = optimization['title'].split()[1]  # Extract package name
            new_version = optimization['title'].split()[-1]  # Extract version

            if dep_name in package_data.get('dependencies', {}):
                package_data['dependencies'][dep_name] = new_version
            elif dep_name in package_data.get('devDependencies', {}):
                package_data['devDependencies'][dep_name] = new_version

            # Update file
            self.repo.update_file(
                path="package.json",
                message=f"Update {dep_name} to {new_version}",
                content=json.dumps(package_data, indent=2),
                sha=file.sha,
                branch=branch
            )

        except Exception as e:
            print(f"Error updating package.json: {e}")

    def _generate_pr_body(
        self,
        optimizations: List[Dict[str, Any]],
        run_date: datetime
    ) -> str:
        """Generate PR description"""
        body = f"""# Monthly Optimizations - {run_date.strftime('%B %Y')}

This PR contains automated optimizations identified by the Monthly Value Agent.

## 📊 Summary

Total optimizations: {len(optimizations)}

"""

        # Group by type
        by_type = {}
        for opt in optimizations:
            opt_type = opt['type']
            if opt_type not in by_type:
                by_type[opt_type] = []
            by_type[opt_type].append(opt)

        # Add database optimizations
        if 'database_index' in by_type:
            body += f"\n### 🗄️ Database Indexes ({len(by_type['database_index'])})\n\n"
            for opt in by_type['database_index']:
                body += f"- [ ] {opt['title']}\n"
                body += f"  - Impact: {opt.get('impact', 'medium')}\n"
                body += f"  - {opt['description']}\n\n"

        # Add dependency updates
        if 'dependency_update' in by_type:
            body += f"\n### 📦 Dependency Updates ({len(by_type['dependency_update'])})\n\n"
            for opt in by_type['dependency_update']:
                body += f"- [ ] {opt['title']}\n"

        body += """
## ✅ Testing Checklist

- [ ] All tests pass
- [ ] No breaking changes introduced
- [ ] Database migrations tested locally
- [ ] Performance impact verified

## 🤖 Automated PR

This PR was automatically generated by the Monthly Value Agent.
Review carefully before merging.

---
*Generated with ❤️ by Crowned Gladiator Enterprises*
"""

        return body
